services:
  - type: web
    name: basel-compliance-app
    runtime: node
    plan: free
    buildCommand: cd client && npm install && npm run build && cd ../server && npm install && npm run build
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: ./database/production.db
