services:
  - type: web
    name: basel-compliance-app
    runtime: node
    plan: free
    buildCommand: npm install && cd client && npm install && cd ../server && npm install && cd .. && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_PATH
        value: ./database/production.db
